# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 7. Reverse a vector (first element becomes last) (★☆☆)

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [44]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

np.dot(A,B)

array([[0.36249447, 0.64883372],
       [0.37097793, 0.15473081],
       [0.47270144, 0.5042887 ],
       [0.87431648, 0.88820139],
       [0.56376925, 0.64466251]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [45]:
import numpy as np

A=np.arange(10)
print(A)
A[(3<A)&(A<8)] = A[(3<A)&(A<8)]*-1
print(A)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [47]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


9
10

0,1,2,3,4를 합한 값에 -1을 더해서 9

-1을 축으로 보아야하기 때문에 10이 나온다.

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Legal: 'Z**Z', '2 << Z >> 2', '1j*Z', 'Z/1/1'

Illegal: 'Z <- Z', 'Z < Z > Z'

파이썬에서 대입 연산자는 <-가 아닌 =이다.

파이썬에서 체인 비교는 불가능하다.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. 0으로 나누는 것은 정의되지 않기 때문에 nan
2. 0으로 나누는 것은 정의되지 않기 때문에 nan
3. nan의 형태를 변환할 수 없으므로 오류

In [4]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-4-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [10]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

common_values = np.intersect1d(Z1,Z2)
print("Z1:", Z1)
print("Z2:", Z2)
print("common_values:", common_values)

Z1: [8 9 5 2 1 6 1 8 1 8]
Z2: [6 2 4 5 7 6 3 9 8 8]
common_values: [2 5 6 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [12]:
np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1)
np.emath.sqrt(-1)

<ipython-input-12-deadca2c2cb6>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
<ipython-input-12-deadca2c2cb6>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


1j

False
np.sqrt(-1)는 nan을 반환, np.emath.sqrt(-1)는 복소수 1j를 반환

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [13]:
dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [15]:
import numpy as np

A = np.array([1, 2, 3, 4], dtype=float)
B = np.array([5, 6, 7, 8])

np.add(A, B, out=A)

np.divide(-A, 2, out=A)

np.negative(A, out=A)

np.multiply(A, A, out=A)

print(A)

[ 9. 16. 25. 36.]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [20]:
A = np.random.uniform(1,10,10)
print(A)

#첫번째 방법
print(A - A%1)

#두번째 방법
print(A // 1)

[9.88546385 3.97662913 4.3336555  1.74009413 5.03321625 9.70336237
 7.82490626 7.72057924 4.5662979  3.82454792]
[9. 3. 4. 1. 5. 9. 7. 7. 4. 3.]
[9. 3. 4. 1. 5. 9. 7. 7. 4. 3.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [22]:
row_values = np.tile(np.arange(5), (5, 1))
print(row_values)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [24]:
A = np.random.random(10)
sorted_A = np.sort(A)

print(A)
print(sorted_A)

[0.42598064 0.38263834 0.40055535 0.03136713 0.48543105 0.86873213
 0.73255713 0.05294879 0.64056884 0.43975844]
[0.03136713 0.05294879 0.38263834 0.40055535 0.42598064 0.43975844
 0.48543105 0.64056884 0.73255713 0.86873213]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [27]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

np.array_equal(A,B)

[1 1 1 1 0]
[1 1 1 0 0]


False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [43]:
cartesian = np.random.rand(10, 2) * 10
print("cartesian coodinate:\n", cartesian)

x = cartesian[:, 0] #x좌표
y = cartesian[:, 1] #y좌표

r = np.sqrt(x**2 + y**2) #반지름r = sqrt(x^2 + y^2) 식 이용
theta = np.arctan2(y, x) #각도 계산

polar_coordinates = np.column_stack((r, theta))
print("\npolar coordinate (r, θ):\n", polar_coordinates)

cartesian coodinate:
 [[7.26941575 8.00609675]
 [6.1684225  1.85295924]
 [2.1335328  7.09248236]
 [4.81198745 1.52967225]
 [4.24587848 0.61002771]
 [3.80496368 6.36979335]
 [5.06263275 1.59352069]
 [1.17877764 1.88190593]
 [7.36460406 5.13773166]
 [6.62843072 0.90499398]]

polar coordinate (r, θ):
 [[10.813972    0.8335871 ]
 [ 6.44072155  0.29181854]
 [ 7.40643425  1.278591  ]
 [ 5.0492693   0.3077858 ]
 [ 4.28947758  0.14269872]
 [ 7.41970457  1.03233138]
 [ 5.30750022  0.30494363]
 [ 2.22060502  1.01120931]
 [ 8.9796258   0.6091302 ]
 [ 6.68992586  0.13569316]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [36]:
Z = np.random.random(10)
print(Z)

Z[Z.argmax()] = 0
print(Z)

[0.783296   0.66558093 0.10366509 0.7091827  0.32680597 0.06643366
 0.71866358 0.3417203  0.1938313  0.76527451]
[0.         0.66558093 0.10366509 0.7091827  0.32680597 0.06643366
 0.71866358 0.3417203  0.1938313  0.76527451]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [37]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z)
print(v)

distances = np.abs(Z - v)
closest_index = np.argmin(distances)
closest_value = Z[closest_index]

print(closest_value)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
45.32231144648665
45


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [38]:
import numpy as np
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [41]:
n = 5
p = 8
Z = np.zeros((n, n))

indices = np.random.choice(range(n * n), p, replace=False)
np.put(Z, indices, 1)

print(Z)

[[0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [28]:
Z = np.random.randint(0,10,(3,3))
print("원래 배열:\n", Z)

원래 배열:
 [[6 2 3]
 [9 0 6]
 [3 4 7]]


In [33]:
# column 1
n = 1
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

1번째 열을 기준으로 정렬된 배열:
 [[3 4 7]
 [6 2 3]
 [9 0 6]]


In [34]:
# column 2
n = 2
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

2번째 열을 기준으로 정렬된 배열:
 [[9 0 6]
 [6 2 3]
 [3 4 7]]


In [32]:
# column 3
n = 3
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

3번째 열을 기준으로 정렬된 배열:
 [[6 2 3]
 [9 0 6]
 [3 4 7]]
